name: clone vgpu driver
on:
  push:
    branches: [ "master" ]
env:
  GITHUB_REPOSITORY: brook-w/NVIDIA-VGPU-Driver-Archive
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    # - name: Download File
    #   uses: robinraju/release-downloader@v1.7
    #   with: 
    #     repository: "justin-himself/NVIDIA-VGPU-Driver-Archive"
    #     tag: "16.2"
    #     fileName: "NVIDIA-GRID-Linux-KVM-535.129.03-537.70.zip"

    - name: Upload File to Release
      run: |
        FILE_PATH='NVIDIA-GRID-Linux-KVM-535.129.03-537.70.zip'
        TAG_NAME='release1'
        RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${TAG_NAME}" | jq -r .id)
        UPLOAD_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/$RELEASE_ID" | jq -r .upload_url)
        UPLOAD_URL="${upload_url/\{?name,label\}/?name=$(basename "$FILE_PATH")}
        touch .work
        ls -al >> .work
        echo $FILE_PATH >> .work
        echo $RELEASE_ID >> .work
        cat .work
        #curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        #     -H "Content-Type: application/octet-stream" --data-binary "@$FILE_PATH" "$UPLOAD_URL"

    # env:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Checkout
    #   uses: actions/checkout@v3
    # - name: Build
    #   run: echo ${{ github.sha }} > Release.txt
    # - name: Test
    #   run: cat Release.txt
    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: Release.txt
