# name: clone vgpu driver
# on:
#   push:
#     branches: [ "master" ]
# jobs:
#   setup-build-publish-deploy:
#     name: Setup
#     runs-on: ubuntu-latest
#     steps:
#     - uses: robinraju/release-downloader@v1.7
#       with: 
#         repository: "justin-himself/NVIDIA-VGPU-Driver-Archive"
#         tag: "16.2"
#         fileName: "NVIDIA-GRID-Linux-KVM-535.129.03-537.70.zip"



name: Download and Push to Release
on:
  push:
    branches:
      - master  # 触发工作流程的分支，可以根据你的需求进行修改
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download File
      run: |
        wget -O wget.zip http://ftp.gnu.org/gnu/wget/wget-1.5.3.tar.gz
        
    - name: Commit and Push to Release Branch
      run: |
        git config --global user.email "1285837374@qq.com"
        git config --global user.name "brook-w"
        git checkout -b release
        git add wget.zip
        git commit -m "Add wget.zip to release branch"
        git push -f origin release

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: wget.zip
        tag: "test"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
